apiVersion: apps/v1
kind: Deployment 
metadata:
  name: appgame-deployment
spec:
  selector:
    matchLabels:
      app: appgame
  replicas: 2 
  template:
    metadata:
      labels:
        app: appgame
    spec:
      containers:
        - name: appgame
          image: irb786/irb:dev 
          ports:
            - containerPort: 8080 


---

apiVersion: v1 
kind: Service
metadata: 
  name: appgame-svc
spec:
  selector:
    app: appgame
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: NodePort 
